CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  mensagem VARCHAR(2000) NOT NULL,
  data_criacao DATETIME NOT NULL,
  status VARCHAR(30) NOT NULL,
  autor VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
